### ISSUE TITLE
Failed ASSERT in finish_emulated_syscall()

### ISSUE THREAD

**Issue by kellerb** [mozilla/rr#1451]
Using latest master (b87a9384fbcfdca154991c975b1c150e7e389bcb)

```
Assertion `(pending_sig() == SIGTRAP || ReplaySession::is_ignored_signal(pending_sig()))' failed to hold. PENDING SIG IS ???signal
```

Please let me know if there is anything I can do to help.

On Ubuntu 14.04

```
uname -a
Linux hostname 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Full output when attempting to replay:
```
irods@hostname:~$ rr ps
PID		PPID	CMD
37195	--		irodsServer
37196	37195	(forked without exec)
37198	37196	irodsReServer
37214	37196	irodsAgent
37217	37196	irodsAgent
37220	37196	irodsAgent
37223	37196	irodsAgent
37226	37196	irodsAgent
37230	37196	irodsAgent
37233	37196	irodsAgent

irods@hostname:~$ rr replay -p 37226
[FATAL /home/kellerb/software/rr/rr/src/task.cc:397:finish_emulated_syscall() errno: 0 'Success'] 
 (task 29816 (rec:37205) at time 131455)
 ->  Assertion `(pending_sig() == SIGTRAP || ReplaySession::is_ignored_signal(pending_sig()))' failed to hold. PENDING SIG IS ???signal
Launch gdb with
  gdb /var/lib/irods/iRODS/server/bin/irodsServer
and attach to the rr debug server with:
  target remote :29816
```

**Comment by khuey** [comment]
Where does the "unknown syscall" bit mentioned in the summary come from?  If the that is what is going on we need the syscallno.

**Comment by kellerb** [comment]
Apologies, I assumed it was an unknown syscall because of the `PENDING SIG IS ???signal` portion of the output. Based on code I added, at the time of the ASSERT, it appears `pending_sig() == 0`.

**Comment by rocallahan** [comment]
I just fixed a problem that might be related to this. Try latest master (e.g. 214f04361c1324fe9b5f1e860e3dd1bec5e39223)?

**Comment by rocallahan** [comment]
Otherwise, try following the instructions and give us a dump of what you see in gdb after attaching (e.g. using `where` to get a backtrace). Another helpful thing would be to run `rr dump -b` and show us a section of the log around `global_time:131455`.

**Comment by kellerb** [comment]
Still seeing the issue on 214f04361c1324fe9b5f1e860e3dd1bec5e39223.

```
irods@hostname:~$ rr dump -b /var/lib/irods/.rr/irodsServer-3 131450-131460
{
  global_time:131450, event:`SYSCALL: select' (state:ENTERING_SYSCALL) tid:28767, ticks:547844
 rax:0xffffffffffffffda rbx:0x1 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x17 rsp:0x2aaab784bc98 r8:0x2aaab784bdf0 r9:0x0 r10:0x0 r11:0x212 r12:0x0 r13:0x0 r14:0x2aaab784c9c0 r15:0x2aaab784bd88 rip:0x70000018 eflags:0x212 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x17}
{
  global_time:131451, event:`SYSCALL: select' (state:EXITING_SYSCALL) tid:28757, ticks:6373709
 rax:0x0 rbx:0x0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7fffffffae70 rdi:0x7 rbp:0x17 rsp:0x7fffffffab08 r8:0x7fffffffacf0 r9:0x1 r10:0x0 r11:0x216 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x7fffffffabf8 rip:0x70000018 eflags:0x216 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x17}
{
  global_time:131452, event:`SYSCALL: wait4' (state:ENTERING_SYSCALL) tid:28757, ticks:6373720
 rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x3 rsi:0x7fffffffac30 rdi:0xffffffffffffffff rbp:0x7fffffffac40 rsp:0x7fffffffac00 r8:0x0 r9:0x1 r10:0x0 r11:0x246 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x0 rip:0x2aaaab5eeee9 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d}
{
  global_time:131453, event:`SYSCALL: wait4' (state:EXITING_SYSCALL) tid:28757, ticks:6373720
 rax:0x0 rbx:0x0 rcx:0xffffffffffffffff rdx:0x3 rsi:0x7fffffffac30 rdi:0xffffffffffffffff rbp:0x7fffffffac40 rsp:0x7fffffffac00 r8:0x0 r9:0x1 r10:0x0 r11:0x246 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x0 rip:0x2aaaab5eeee9 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d}
{
  global_time:131454, event:`SYSCALL: select' (state:ENTERING_SYSCALL) tid:28757, ticks:6373793
 rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7fffffffae70 rdi:0x7 rbp:0x17 rsp:0x7fffffffab08 r8:0x7fffffffacf0 r9:0x1 r10:0x0 r11:0x216 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x7fffffffabf8 rip:0x70000018 eflags:0x216 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x17}
{
  global_time:131455, event:`SYSCALL: select' (state:EXITING_SYSCALL) tid:28757, ticks:6373793
 rax:0x0 rbx:0x0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7fffffffae70 rdi:0x7 rbp:0x17 rsp:0x7fffffffab08 r8:0x7fffffffacf0 r9:0x1 r10:0x0 r11:0x216 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x7fffffffabf8 rip:0x70000018 eflags:0x216 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x17}
{
  global_time:131456, event:`SYSCALL: wait4' (state:ENTERING_SYSCALL) tid:28757, ticks:6373804
 rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x3 rsi:0x7fffffffac30 rdi:0xffffffffffffffff rbp:0x7fffffffac40 rsp:0x7fffffffac00 r8:0x0 r9:0x1 r10:0x0 r11:0x246 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x0 rip:0x2aaaab5eeee9 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d}
{
  global_time:131457, event:`SYSCALL: wait4' (state:EXITING_SYSCALL) tid:28757, ticks:6373804
 rax:0x0 rbx:0x0 rcx:0xffffffffffffffff rdx:0x3 rsi:0x7fffffffac30 rdi:0xffffffffffffffff rbp:0x7fffffffac40 rsp:0x7fffffffac00 r8:0x0 r9:0x1 r10:0x0 r11:0x246 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x0 rip:0x2aaaab5eeee9 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d}
{
  global_time:131458, event:`SYSCALL: select' (state:ENTERING_SYSCALL) tid:28757, ticks:6373877
 rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7fffffffae70 rdi:0x7 rbp:0x17 rsp:0x7fffffffab08 r8:0x7fffffffacf0 r9:0x1 r10:0x0 r11:0x216 r12:0x5534d0 r13:0x7fffffffeaf0 r14:0x0 r15:0x7fffffffabf8 rip:0x70000018 eflags:0x216 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x17}
{
  global_time:131459, event:`SYSCALL: select' (state:EXITING_SYSCALL) tid:28767, ticks:547844
 rax:0x0 rbx:0x1 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x17 rsp:0x2aaab784bc98 r8:0x2aaab784bdf0 r9:0x0 r10:0x0 r11:0x212 r12:0x0 r13:0x0 r14:0x2aaab784c9c0 r15:0x2aaab784bd88 rip:0x70000018 eflags:0x212 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x17}
{
  global_time:131460, event:`SYSCALL: select' (state:ENTERING_SYSCALL) tid:28767, ticks:547896
 rax:0xffffffffffffffda rbx:0x1 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x17 rsp:0x2aaab784bc98 r8:0x2aaab784bdf0 r9:0x0 r10:0x0 r11:0x212 r12:0x0 r13:0x0 r14:0x2aaab784c9c0 r15:0x2aaab784bd88 rip:0x70000018 eflags:0x212 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x17}
```

There are eleven threads:
```
(gdb) info threads
  Id   Target Id         Frame 
  11   Thread 28769 (irodsServer) 0x0000000070000018 in ?? ()
  10   Thread 28768 (irodsServer) 0x0000000070000018 in ?? ()
  9    Thread 28767 (irodsServer) 0x0000000070000018 in ?? ()
  8    Thread 28765 (irodsServer) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 28764 (irodsServer) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 28763 (irodsServer) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 28762 (irodsServer) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 28761 (irodsServer) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 28760 (irodsServer) 0x0000000070000004 in ?? ()
  2    Thread 28757 (irodsServer) 0x0000000070000018 in ?? ()
* 1    Thread 28766 (irodsServer) pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
```

```
(gdb) thread 1
[Switching to thread 1 (Thread 28766)]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
(gdb) where 
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000055e253 in boost::condition_variable::wait (this=0xf1e3c0 <SpawnReqCond>, m=...) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/pthread/condition_variable.hpp:73
#2  0x0000000000557882 in spawnManagerTask () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1152
#3  0x00000000005693e5 in boost::detail::thread_data<void (*)()>::run (this=0x117fc20) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:116
#4  0x0000000000985743 in thread_proxy ()
#5  0x00002aaaaaed1934 in thread_trampoline (arg=0x117fe10) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#6  0x00002aaaab5e7182 in start_thread (arg=0x2aaab6e4b700) at pthread_create.c:312
#7  0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 2
[Switching to thread 2 (Thread 28757)]
#0  0x0000000070000018 in ?? ()
(gdb) where
#0  0x0000000070000018 in ?? ()
#1  0x00002aaaaaed2b2e in _traced_raw_syscall () at /home/kellerb/software/rr/rr/src/preload/traced_syscall_shared.S:67
#2  0x00002aaaaaed0f73 in traced_raw_syscall (call=call@entry=0x7fffffffabf8) at /home/kellerb/software/rr/rr/src/preload/preload.c:295
#3  0x00002aaaaaed2078 in syscall_hook_internal (call=0x7fffffffabf8) at /home/kellerb/software/rr/rr/src/preload/preload.c:1705
#4  syscall_hook (call=0x7fffffffabf8) at /home/kellerb/software/rr/rr/src/preload/preload.c:1713
#5  0x00002aaaaaed2b62 in _syscall_hook_trampoline () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:135
#6  0x00002aaaaaed2b7f in _syscall_hook_trampoline_48_8b_3c_24 () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:192
#7  0x00002aaaac649da6 in select () at ../sysdeps/unix/syscall-template.S:81
#8  0x0000000000554fa7 in serverMain (logDir=0x0) at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:362
#9  0x0000000000554a3b in main (argc=1, argv=0x7fffffffeaf8) at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:245
```

```
(gdb) thread 3
[Switching to thread 3 (Thread 28760)]
#0  0x0000000070000004 in ?? ()
(gdb) where
#0  0x0000000070000004 in ?? ()
#1  0x00002aaaaaed2b4a in _untraced_raw_syscall () at /home/kellerb/software/rr/rr/src/preload/traced_syscall_shared.S:67
#2  0x00002aaaaaed289b in untraced_syscall (a5=0, a4=0, a3=0, a2=500, a1=1, a0=46912713838616, syscallno=7) at /home/kellerb/software/rr/rr/src/preload/preload.c:417
#3  sys_poll (call=0x2aaab3244858) at /home/kellerb/software/rr/rr/src/preload/preload.c:1440
#4  syscall_hook_internal (call=0x2aaab3244858) at /home/kellerb/software/rr/rr/src/preload/preload.c:1678
#5  syscall_hook (call=0x2aaab3244858) at /home/kellerb/software/rr/rr/src/preload/preload.c:1713
#6  0x00002aaaaaed2b62 in _syscall_hook_trampoline () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:135
#7  0x00002aaaaaed2b7f in _syscall_hook_trampoline_48_8b_3c_24 () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:192
#8  0x00002aaaac645130 in poll () at ../sysdeps/unix/syscall-template.S:81
#9  0x00000000009cbf76 in zmq::signaler_t::wait (this=0x2aaab80039c0, timeout_=500) at signaler.cpp:222
#10 0x00000000009c421e in zmq::mailbox_t::recv (this=0x2aaab8003960, cmd_=0x2aaab3244910, timeout_=500) at mailbox.cpp:72
#11 0x00000000009cc9a4 in zmq::socket_base_t::process_commands (this=0x2aaab8003660, timeout_=<optimized out>, throttle_=false) at socket_base.cpp:884
#12 0x00000000009ccbea in zmq::socket_base_t::recv (this=0x2aaab8003660, msg_=0x2aaab3244df0, flags_=<optimized out>) at socket_base.cpp:818
#13 0x00000000009bbfa9 in s_recvmsg (s_=0x2aaab32448b0, msg_=0x1, flags_=500) at zmq.cpp:460
#14 0x00000000006c60cd in zmq::socket_t::recv (this=0x2aaab3244ae0, msg_=0x2aaab3244df0, flags_=0) at /home/kellerb/software/irods/iRODS/../external/zeromq-4.0.5/include/zmq.hpp:456
#15 0x00000000006bcb1c in irods::server_control_executor::operator() (this=0x7fffffffae10) at /home/kellerb/software/irods/iRODS/server/core/src/irods_server_control_plane.cpp:512
#16 0x00000000006cb329 in boost::detail::thread_data<boost::reference_wrapper<irods::server_control_executor> >::run (this=0x1180980) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:136
#17 0x0000000000985743 in thread_proxy ()
#18 0x00002aaaaaed1934 in thread_trampoline (arg=0x11730f0) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#19 0x00002aaaab5e7182 in start_thread (arg=0x2aaab3245700) at pthread_create.c:312
#20 0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 4
[Switching to thread 4 (Thread 28761)]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
(gdb) where
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000055e253 in boost::condition_variable::wait (this=0xf1e360 <ReadReqCond>, m=...) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/pthread/condition_variable.hpp:73
#2  0x0000000000556e64 in getConnReqFromQue () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1020
#3  0x0000000000557299 in readWorkerTask () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1080
#4  0x00000000005693e5 in boost::detail::thread_data<void (*)()>::run (this=0x11404a0) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:116
#5  0x0000000000985743 in thread_proxy ()
#6  0x00002aaaaaed1934 in thread_trampoline (arg=0x116c370) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#7  0x00002aaaab5e7182 in start_thread (arg=0x2aaab3c46700) at pthread_create.c:312
#8  0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 5
[Switching to thread 5 (Thread 28762)]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
(gdb) where
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000055e253 in boost::condition_variable::wait (this=0xf1e360 <ReadReqCond>, m=...) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/pthread/condition_variable.hpp:73
#2  0x0000000000556e64 in getConnReqFromQue () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1020
#3  0x0000000000557299 in readWorkerTask () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1080
#4  0x00000000005693e5 in boost::detail::thread_data<void (*)()>::run (this=0x117ec40) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:116
#5  0x0000000000985743 in thread_proxy ()
#6  0x00002aaaaaed1934 in thread_trampoline (arg=0x11445f0) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#7  0x00002aaaab5e7182 in start_thread (arg=0x2aaab4647700) at pthread_create.c:312
#8  0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 6 
[Switching to thread 6 (Thread 28763)]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
(gdb) where
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000055e253 in boost::condition_variable::wait (this=0xf1e360 <ReadReqCond>, m=...) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/pthread/condition_variable.hpp:73
#2  0x0000000000556e64 in getConnReqFromQue () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1020
#3  0x0000000000557299 in readWorkerTask () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1080
#4  0x00000000005693e5 in boost::detail::thread_data<void (*)()>::run (this=0x117ef60) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:116
#5  0x0000000000985743 in thread_proxy ()
#6  0x00002aaaaaed1934 in thread_trampoline (arg=0x117f150) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#7  0x00002aaaab5e7182 in start_thread (arg=0x2aaab5048700) at pthread_create.c:312
#8  0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 7
[Switching to thread 7 (Thread 28764)]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
(gdb) where
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000055e253 in boost::condition_variable::wait (this=0xf1e360 <ReadReqCond>, m=...) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/pthread/condition_variable.hpp:73
#2  0x0000000000556e64 in getConnReqFromQue () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1020
#3  0x0000000000557299 in readWorkerTask () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1080
#4  0x00000000005693e5 in boost::detail::thread_data<void (*)()>::run (this=0x117f520) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:116
#5  0x0000000000985743 in thread_proxy ()
#6  0x00002aaaaaed1934 in thread_trampoline (arg=0x117f710) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#7  0x00002aaaab5e7182 in start_thread (arg=0x2aaab5a49700) at pthread_create.c:312
#8  0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 8
[Switching to thread 8 (Thread 28765)]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
(gdb) where
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000055e253 in boost::condition_variable::wait (this=0xf1e360 <ReadReqCond>, m=...) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/pthread/condition_variable.hpp:73
#2  0x0000000000556e64 in getConnReqFromQue () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1020
#3  0x0000000000557299 in readWorkerTask () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1080
#4  0x00000000005693e5 in boost::detail::thread_data<void (*)()>::run (this=0x117f8a0) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:116
#5  0x0000000000985743 in thread_proxy ()
#6  0x00002aaaaaed1934 in thread_trampoline (arg=0x117fa90) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#7  0x00002aaaab5e7182 in start_thread (arg=0x2aaab644a700) at pthread_create.c:312
#8  0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 9
[Switching to thread 9 (Thread 28767)]
#0  0x0000000070000018 in ?? ()
(gdb) where
#0  0x0000000070000018 in ?? ()
#1  0x00002aaaaaed2b2e in _traced_raw_syscall () at /home/kellerb/software/rr/rr/src/preload/traced_syscall_shared.S:67
#2  0x00002aaaaaed0f73 in traced_raw_syscall (call=call@entry=0x2aaab784bd88) at /home/kellerb/software/rr/rr/src/preload/preload.c:295
#3  0x00002aaaaaed2078 in syscall_hook_internal (call=0x2aaab784bd88) at /home/kellerb/software/rr/rr/src/preload/preload.c:1705
#4  syscall_hook (call=0x2aaab784bd88) at /home/kellerb/software/rr/rr/src/preload/preload.c:1713
#5  0x00002aaaaaed2b62 in _syscall_hook_trampoline () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:135
#6  0x00002aaaaaed2b7f in _syscall_hook_trampoline_48_8b_3c_24 () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:192
#7  0x00002aaaac649da6 in select () at ../sysdeps/unix/syscall-template.S:81
#8  0x000000000058a801 in rodsSleep (sec=0, microSec=500) at /home/kellerb/software/irods/iRODS/lib/core/src/sockComm.cpp:1357
#9  0x0000000000558128 in purgeLockFileWorkerTask () at /home/kellerb/software/irods/iRODS/server/core/src/rodsServer.cpp:1289
#10 0x00000000005693e5 in boost::detail::thread_data<void (*)()>::run (this=0x117ffa0) at /home/kellerb/software/irods/external/boost_1_57_0/boost/thread/detail/thread.hpp:116
#11 0x0000000000985743 in thread_proxy ()
#12 0x00002aaaaaed1934 in thread_trampoline (arg=0x1180190) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#13 0x00002aaaab5e7182 in start_thread (arg=0x2aaab784c700) at pthread_create.c:312
#14 0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 10
[Switching to thread 10 (Thread 28768)]
#0  0x0000000070000018 in ?? ()
(gdb) where
#0  0x0000000070000018 in ?? ()
#1  0x00002aaaaaed2b2e in _traced_raw_syscall () at /home/kellerb/software/rr/rr/src/preload/traced_syscall_shared.S:67
#2  0x00002aaaaaed0f73 in traced_raw_syscall (call=call@entry=0x2aaabc7ff178) at /home/kellerb/software/rr/rr/src/preload/preload.c:295
#3  0x00002aaaaaed2078 in syscall_hook_internal (call=0x2aaabc7ff178) at /home/kellerb/software/rr/rr/src/preload/preload.c:1705
#4  syscall_hook (call=0x2aaabc7ff178) at /home/kellerb/software/rr/rr/src/preload/preload.c:1713
#5  0x00002aaaaaed2b62 in _syscall_hook_trampoline () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:135
#6  0x00002aaaaaed2b7f in _syscall_hook_trampoline_48_8b_3c_24 () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:192
#7  0x00002aaaac652b16 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#8  0x00000000009c2ead in zmq::epoll_t::loop (this=0x2aaab8000940) at epoll.cpp:145
#9  0x00000000009d62db in thread_routine (arg_=0x2aaab80009b0) at thread.cpp:81
#10 0x00002aaaaaed1934 in thread_trampoline (arg=0x2aaab8000c10) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#11 0x00002aaaab5e7182 in start_thread (arg=0x2aaabc800700) at pthread_create.c:312
#12 0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) thread 11
[Switching to thread 11 (Thread 28769)]
#0  0x0000000070000018 in ?? ()
(gdb) where
#0  0x0000000070000018 in ?? ()
#1  0x00002aaaaaed2b2e in _traced_raw_syscall () at /home/kellerb/software/rr/rr/src/preload/traced_syscall_shared.S:67
#2  0x00002aaaaaed0f73 in traced_raw_syscall (call=call@entry=0x2aaabd000178) at /home/kellerb/software/rr/rr/src/preload/preload.c:295
#3  0x00002aaaaaed2078 in syscall_hook_internal (call=0x2aaabd000178) at /home/kellerb/software/rr/rr/src/preload/preload.c:1705
#4  syscall_hook (call=0x2aaabd000178) at /home/kellerb/software/rr/rr/src/preload/preload.c:1713
#5  0x00002aaaaaed2b62 in _syscall_hook_trampoline () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:135
#6  0x00002aaaaaed2b7f in _syscall_hook_trampoline_48_8b_3c_24 () at /home/kellerb/software/rr/rr/src/preload/syscall_hook.S:192
#7  0x00002aaaac652b16 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#8  0x00000000009c2ead in zmq::epoll_t::loop (this=0x2aaab8003480) at epoll.cpp:145
#9  0x00000000009d62db in thread_routine (arg_=0x2aaab80034f0) at thread.cpp:81
#10 0x00002aaaaaed1934 in thread_trampoline (arg=0x2aaab80008e0) at /home/kellerb/software/rr/rr/src/preload/preload.c:655
#11 0x00002aaaab5e7182 in start_thread (arg=0x2aaabd001700) at pthread_create.c:312
#12 0x00002aaaac65247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by rocallahan** [comment]
OK, one thing that seems weird here is that the assertion you hit is guarded by `if (!known_idempotent_insn_after_syscall)`. But `known_idempotent_insn_after_syscall` should be true since we're in a traced syscall, i.e. `is_in_traced_syscall()` should have been true in `Task::finish_emulated_syscall()`. Apparently it wasn't. Can you report the value of `ip` when the assertion fires? The value of `t->wait_status` could be useful too.

**Comment by kellerb** [comment]
```
(gdb) frame 6
#6  0x000000000060037d in Task::finish_emulated_syscall (this=0x2697eb0) at /home/kellerb/software/rr/rr/src/task.cc:396
396	    ASSERT(this, (pending_sig() == SIGTRAP ||
(gdb) print ip
$1 = {ptr = 46912507917332}
(gdb) print wait_status
$2 = 34175
```
I assumed that `t->wait_status` meant `this->wait_status`.
I got this information by attaching to the running rr instance:
```
(gdb) where
#0  0x00007f76f8fd2ac7 in accept4 (fd=32, addr=..., addr_len=0x7fff2759333c, flags=-1) at ../sysdeps/unix/sysv/linux/accept4.c:33
#1  0x0000000000559ed0 in GdbConnection::await_debugger (this=0x32268a0, listen_fd=...) at /home/kellerb/software/rr/rr/src/GdbConnection.cc:109
#2  0x000000000055a15d in GdbConnection::await_client_connection (desired_port=30515, probe=GdbConnection::PROBE_PORT, tgid=28757, exe_image=..., features=..., client_params_fd=0x0) at /home/kellerb/software/rr/rr/src/GdbConnection.cc:145
#3  0x0000000000566641 in GdbServer::emergency_debug (t=0x2697eb0) at /home/kellerb/software/rr/rr/src/GdbServer.cc:989
#4  0x000000000057ebae in emergency_debug (t=0x2697eb0) at /home/kellerb/software/rr/rr/src/log.cc:20
#5  0x000000000057ec70 in EmergencyDebugOstream::~EmergencyDebugOstream (this=0x7fff275946f0, __in_chrg=<optimized out>) at /home/kellerb/software/rr/rr/src/log.cc:27
#6  0x000000000060037d in Task::finish_emulated_syscall (this=0x2697eb0) at /home/kellerb/software/rr/rr/src/task.cc:396
#7  0x00000000005f2f9f in Session::copy_state_to (this=0x7f76f9fed010, dest=..., dest_emu_fs=...) at /home/kellerb/software/rr/rr/src/Session.cc:403
#8  0x00000000005c2a72 in ReplaySession::clone (this=0x7f76f9fed010) at /home/kellerb/software/rr/rr/src/ReplaySession.cc:95
#9  0x00000000005dac5a in ReplayTimeline::add_explicit_checkpoint (this=0x7fff275954d8) at /home/kellerb/software/rr/rr/src/ReplayTimeline.cc:262
#10 0x00000000005df32d in ReplayTimeline::maybe_add_reverse_exec_checkpoint (this=0x7fff275954d8, strategy=ReplayTimeline::LOW_OVERHEAD) at /home/kellerb/software/rr/rr/src/ReplayTimeline.cc:998
#11 0x00000000005def32 in ReplayTimeline::replay_step (this=0x7fff275954d8, command=RUN_CONTINUE, direction=RUN_FORWARD, stop_at_time=0) at /home/kellerb/software/rr/rr/src/ReplayTimeline.cc:879
#12 0x00000000005658ef in GdbServer::replay_one_step (this=0x7fff275954b0) at /home/kellerb/software/rr/rr/src/GdbServer.cc:787
#13 0x0000000000566245 in GdbServer::serve_replay (this=0x7fff275954b0, flags=...) at /home/kellerb/software/rr/rr/src/GdbServer.cc:938
#14 0x00000000005c1f79 in GdbServer::serve (session=..., target=..., flags=..., session_flags=...) at /home/kellerb/software/rr/rr/src/GdbServer.h:50
#15 0x00000000005c119d in replay (trace_dir=..., flags=...) at /home/kellerb/software/rr/rr/src/ReplayCommand.cc:350
#16 0x00000000005c184e in ReplayCommand::run (this=0x8a99f0 <ReplayCommand::singleton>, args=...) at /home/kellerb/software/rr/rr/src/ReplayCommand.cc:416
#17 0x0000000000580771 in main (argc=4, argv=0x7fff275959f8) at /home/kellerb/software/rr/rr/src/main.cc:258
```

**Comment by rocallahan** [comment]
What is in the tracee at address 46912507917332? Try disassembling at that location...

**Comment by kellerb** [comment]
```
(gdb) p/x ip
$4 = {ptr = 0x2aaaab5eb414}
(gdb) print *0x2aaaab5eb414
Cannot access memory at address 0x2aaaab5eb414
```

**Comment by kellerb** [comment]
Oops, sorry, that wasn't in the tracee.

**Comment by kellerb** [comment]
```
(gdb) info line *46912507917332
Line 185 of "../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S" starts at address 0x2aaaab5eb414 <pthread_cond_wait@@GLIBC_2.3.2+196> and ends at 0x2aaaab5eb417 <pthread_cond_wait@@GLIBC_2.3.2+199>.
```
```
(gdb) disassemble /mr 46912507917332,+32
Dump of assembler code from 0x2aaaab5eb414 to 0x2aaaab5eb434:
185     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
=> 0x00002aaaab5eb414 <pthread_cond_wait@@GLIBC_2.3.2+196>:     8b 3c 24        mov    (%rsp),%edi

186     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb417 <pthread_cond_wait@@GLIBC_2.3.2+199>:     e8 64 2a 00 00  callq  0x2aaaab5ede80 <__pthread_disable_asynccancel>

187     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
188     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
189     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
190     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb41c <pthread_cond_wait@@GLIBC_2.3.2+204>:     48 8b 7c 24 08  mov    0x8(%rsp),%rdi

191     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb421 <pthread_cond_wait@@GLIBC_2.3.2+209>:     be 01 00 00 00  mov    $0x1,%esi

192     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb426 <pthread_cond_wait@@GLIBC_2.3.2+214>:     31 c0   xor    %eax,%eax

193     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb428 <pthread_cond_wait@@GLIBC_2.3.2+216>:     f0 0f b1 37     lock cmpxchg %esi,(%rdi)

194     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
195     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb429 <pthread_cond_wait@@GLIBC_2.3.2+217>:     0f b1 37        cmpxchg %esi,(%rdi)

196     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
197     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
198     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
199     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb42c <pthread_cond_wait@@GLIBC_2.3.2+220>:     0f 85 e0 00 00 00       jne    0x2aaaab5eb512 <pthread_cond_wait@@GLIBC_2.3.2+450>

200     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
201     in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
   0x00002aaaab5eb432 <pthread_cond_wait@@GLIBC_2.3.2+226>:     8b 57 2c        mov    0x2c(%rdi),%edx

End of assembler dump.
```

**Comment by rocallahan** [comment]
When the assertion fails, can you print the contents of `this->regs()`? I'm still having difficulty understanding what could be happening here...

**Comment by kellerb** [comment]
```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7faaf06ee780 (LWP 30852) "rr" 0x00007faaef5c3110 in __poll_nocancel () at ../sysdeps/unix/syscall-template.S:81
```
```
(gdb) where
#0  0x00007faaef5c3110 in __poll_nocancel () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000055abff in poll_socket (sock_fd=..., events=1, timeoutMs=-1) at /home/kellerb/software/rr/rr/src/GdbConnection.cc:231
#2  0x000000000055ac99 in poll_incoming (sock_fd=..., timeoutMs=-1) at /home/kellerb/software/rr/rr/src/GdbConnection.cc:239
#3  0x000000000055ace4 in GdbConnection::read_data_once (this=0x23f08a0) at /home/kellerb/software/rr/rr/src/GdbConnection.cc:253
#4  0x000000000055b7e8 in GdbConnection::read_packet (this=0x23f08a0) at /home/kellerb/software/rr/rr/src/GdbConnection.cc:433
#5  0x000000000055ea70 in GdbConnection::get_request (this=0x23f08a0) at /home/kellerb/software/rr/rr/src/GdbConnection.cc:1112
#6  0x0000000000564f0c in GdbServer::process_debugger_requests (this=0x7fffadefd380, t=0x1861eb0) at /home/kellerb/software/rr/rr/src/GdbServer.cc:679
#7  0x0000000000566686 in GdbServer::emergency_debug (t=0x1861eb0) at /home/kellerb/software/rr/rr/src/GdbServer.cc:991
#8  0x000000000057ebae in emergency_debug (t=0x1861eb0) at /home/kellerb/software/rr/rr/src/log.cc:20
#9  0x000000000057ec70 in EmergencyDebugOstream::~EmergencyDebugOstream (this=0x7fffadefd630, __in_chrg=<optimized out>) at /home/kellerb/software/rr/rr/src/log.cc:27
#10 0x000000000060037d in Task::finish_emulated_syscall (this=0x1861eb0) at /home/kellerb/software/rr/rr/src/task.cc:396
#11 0x00000000005f2f9f in Session::copy_state_to (this=0x7faaf05ec010, dest=..., dest_emu_fs=...) at /home/kellerb/software/rr/rr/src/Session.cc:403
#12 0x00000000005c2a72 in ReplaySession::clone (this=0x7faaf05ec010) at /home/kellerb/software/rr/rr/src/ReplaySession.cc:95
#13 0x00000000005dac5a in ReplayTimeline::add_explicit_checkpoint (this=0x7fffadefe418) at /home/kellerb/software/rr/rr/src/ReplayTimeline.cc:262
#14 0x00000000005df32d in ReplayTimeline::maybe_add_reverse_exec_checkpoint (this=0x7fffadefe418, strategy=ReplayTimeline::LOW_OVERHEAD) at /home/kellerb/software/rr/rr/src/ReplayTimeline.cc:998
#15 0x00000000005def32 in ReplayTimeline::replay_step (this=0x7fffadefe418, command=RUN_CONTINUE, direction=RUN_FORWARD, stop_at_time=0) at /home/kellerb/software/rr/rr/src/ReplayTimeline.cc:879
#16 0x00000000005658ef in GdbServer::replay_one_step (this=0x7fffadefe3f0) at /home/kellerb/software/rr/rr/src/GdbServer.cc:787
#17 0x0000000000566245 in GdbServer::serve_replay (this=0x7fffadefe3f0, flags=...) at /home/kellerb/software/rr/rr/src/GdbServer.cc:938
#18 0x00000000005c1f79 in GdbServer::serve (session=..., target=..., flags=..., session_flags=...) at /home/kellerb/software/rr/rr/src/GdbServer.h:50
#19 0x00000000005c119d in replay (trace_dir=..., flags=...) at /home/kellerb/software/rr/rr/src/ReplayCommand.cc:350
#20 0x00000000005c184e in ReplayCommand::run (this=0x8a99f0 <ReplayCommand::singleton>, args=...) at /home/kellerb/software/rr/rr/src/ReplayCommand.cc:416
#21 0x0000000000580771 in main (argc=4, argv=0x7fffadefe938) at /home/kellerb/software/rr/rr/src/main.cc:258
```
```
(gdb) frame 10
#10 0x000000000060037d in Task::finish_emulated_syscall (this=0x1861eb0) at /home/kellerb/software/rr/rr/src/task.cc:396
396	    ASSERT(this, (pending_sig() == SIGTRAP ||
```
```
(gdb) print this->regs()
$1 = (const Registers &) @0x1862018: {u = {x86regs = {ebx = -1226524928, ecx = 10922, edx = -1226524224, esi = 10922, edi = 0, ebp = 0, eax = 0, xds = 0, xes = -1226527232, xfs = 10922, xgs = 1, orig_eax = 0, eip = 582, xcs = 0, eflags = 0, esp = 0, xss = 1}, x64regs = {r15 = 46912701249280, r14 = 46912701249984, r13 = 0, r12 = 0, rbp = 46912701246976, rbx = 1, r11 = 582, r10 = 0, r9 = 1, r8 = 15852288, 
      rax = 18446744073709551578, rcx = 18446744073709551615, rdx = 3, rsi = 128, rdi = 15852524, orig_rax = 202, rip = 46912507917332, cs = 51, cs_upper = 0, eflags = 582, eflags_upper = 0, rsp = 46912701246816, ss = 43, ss_upper = 0, fs_base = 46912701249280, gs_base = 0, ds = 0, ds_upper = 0, es = 0, es_upper = 0, fs = 0, fs_upper = 0, gs = 0, gs_upper = 0}}, arch_ = x86_64}
```

**Comment by rocallahan** [comment]
OK ... so it looks like IP doesn't advance during the `cont_sysemu_singlestep()`. Yet, as far as I can imagine, this could only happen by hitting the breakpoint or receiving a signal instead, neither of which would receive a `wait_status` of 0.

If you simply comment out that assertion, does everything work?

**Comment by rocallahan** [comment]
Another shot in the dark: replace `cont_sysemu_singlestep` with `cont_singlestep` in `finish_emulated_syscall`, and see if that helps.

**Comment by kellerb** [comment]
I rebuilt with the latest (734684a37819df23a1fcdf549c74493a873343f7) and, along with a newer build of the tracee, am no longer experiencing the issue.

I can rebuild with the previous commit if you would like me to re-replicate and continue investigating.

The issue was noticed while using rr to debug a workflow that started with a server process and ended up following six forked children. The issue was seen while attempting to replay (I believe) four of the six children. I am now able to replay all of the child processes without error.

---
As an aside, rr is awesome. The application I work on has gone from borderline-impossible to use inside a debugger to comically easy. I've got all my coworkers hooked on it.

**Comment by rocallahan** [comment]
> As an aside, rr is awesome.

Great to hear :-). Maybe you could leave a testimonial here? https://github.com/mozilla/rr/wiki/Testimonials

> I can rebuild with the previous commit if you would like me to re-replicate and continue investigating.

Since I have no good ideas at this stage, let's shelve it for now. Thanks!

**Comment by rocallahan** [comment]
I'm getting this myself in a reproducible way.

**Comment by rocallahan** [comment]
We're trying to make a clone at a syscall interruption. `rep_process_syscall_arch` has taken the interruption path that does `set_return_value_from_trace` and sets `step->action` to `TSTEP_RETIRE`, and then we exited out to `ReplayTimeline` which then tries to make a clone in this state, and that's when things go wrong.

I wonder if that `rep_process_syscall_arch` path needs to call `finish_emulated_syscall` before resetting the registers. I suspect it's the register reset while we're in an emulated syscall that is somehow tripping us up here. I'll look into this more soon.

**Comment by rocallahan** [comment]
Having trouble reproducing this in a small testcase :-(

**Comment by rocallahan** [comment]
One interesting thing is that when this fails, the `cont_sysemu_singlestep` changes $rax from `0xfffffffffffffe00` (`-ERESTARTSYS`) to `0xffffffffffffffda` (`-ENOSYS`).

**Comment by rocallahan** [comment]
... it's like we actually tried to reexecute the syscall with an invalid syscall number.

**Comment by rocallahan** [comment]
Next I'll try examining `/proc/pid/stack` to see if that illuminates the states these processes are actually in...

**Comment by rocallahan** [comment]
In the failing case, the kernel stack before we do `finish_emulated_syscall` looks like this:
````
[<ffffffff8109f793>] ptrace_stop+0x153/0x270
[<ffffffff810a1245>] get_signal+0x365/0x5f0
[<ffffffff810134f7>] do_signal+0x37/0x740
[<ffffffff81013c69>] do_notify_resume+0x69/0xb0
[<ffffffff81730d22>] paranoid_userspace+0x46/0x50
````
This indicates that the task is stopped during a return to userspace. In other words, the syscall was already finished, probably due to it being cloned from another session, which already forced the syscall to finish. We should handle this OK, but I think what might be happening is that the kernel looks at the current state of the task --- just after a syscall instruction, $rax `-ERESTARTSYS`, and decides that the syscall needs to be restarted.

**Comment by rocallahan** [comment]
OK, I finally have a small testcase for this!

**Comment by rocallahan** [comment]
Resolved by 0d1748767b834e8af6d8702de8b8b44e369453c7
