### ISSUE TITLE
replay divergence on some hardware when replaying Firefox (regression)

### ISSUE THREAD

**Issue by dbaron** [mozilla/rr#1603]
A recent regression in rr has caused replay divergence on *one but not both* of my computers when recording and replaying Firefox.

I have two computers runing Ubuntu 15.04.  The laptop's CPU is a i7-4600U; the (much older) desktop's CPU is an Xeon W3520.

````
$ rr replay -a

rr: Warning: Your CPU frequency governor is 'powersave'.  rr strongly
    recommends that you use the 'performance' governor.  Not using the
    'performance' governor can cause rr to be at least 2x slower
    on laptops.

    On Fedora-based systems, you can enable the 'performance' governor
    by running the following commands:

    $ sudo dnf install kernel-tools
    $ sudo cpupower frequency-set -g performance

[ERROR /home/dbaron/builds/rr/rr/src/ReplaySession.cc:452:guard_overshoot() errno: 0 'Success'] 
 -> Replay diverged.  Dumping register comparison.
[FATAL /home/dbaron/builds/rr/rr/src/ReplaySession.cc:468:guard_overshoot() errno: 0 'Success'] 
 (task 25375 (rec:25259) at time 3334)
 ->  Assertion `false' failed to hold. overshot target ticks=27385242 by 12288
Launch gdb with
  gdb /hdd/builds/build-mozilla-central/obj/firefox-debugopt/dist/bin/firefox
and attach to the rr debug server with:
  target remote :25375
````

git bisect says this is a regression from:
````
36ac389649e3e84caa46d64487813c018857f831 is the first bad commit
commit 36ac389649e3e84caa46d64487813c018857f831
Author: Robert O'Callahan <robert@ocallahan.org>
Date:   Thu Nov 26 10:23:53 2015 +1300

    Clear %r11 on syscall exits.
    
    This will give us consistent values for %r11 even if we replace the syscall
    instruction with noops. Emulating the move from RFLAGS to r11 would be
    annoying and pointless.

:040000 040000 f8cb9d5db4f293f108b008ad9774c2304ec460c3 cb7216487fdf62ab0ff324b3f1a3738586e5399f M      src
````

(although I'm actually not 100% sure that's the right regression range since the error on master is not quite as fast as it was right after that commit, although maybe how quickly the error happens varies a bit)

**Comment by dbaron** [comment]
Oh, and the point I missed is that this bug shows up on the laptop but does not show up on the desktop.

**Comment by rocallahan** [comment]
Thanks for the regression range. That helps a lot.

I need the part of `rr dump -b -m -p` around the event where we diverged.

**Comment by dbaron** [comment]
This time the error was:
> [ERROR /home/dbaron/builds/rr/rr/src/ReplaySession.cc:505:guard_overshoot() errno: 0 'Success'] 
>  -> Replay diverged.  Dumping register comparison.
> [FATAL /home/dbaron/builds/rr/rr/src/ReplaySession.cc:521:guard_overshoot() errno: 0 'Success'] 
>  (task 18011 (rec:17902) at time 21343)
>  ->  Assertion `false' failed to hold. overshot target ticks=72417207 by 116078
> Launch gdb with
>   gdb /hdd/builds/build-mozilla-central/obj/firefox-debugopt/dist/bin/plugin-container
> and attach to the rr debug server with:
>   target remote :18011


And the dump around that time is:
> {
>   global_time:21337, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:17902, ticks:71795858
>  rax:0xffffffffffffffda rbx:0xb rcx:0xffffffffffffffff rdx:0x0 rsi:0x8a38 rdi:0x7ff1b7e87000 rbp:0x7ffdde68aba0 rsp:0x7ffdde68a950 r8:0x17d4ca0 r9:0x0 r10:0x7ff1b06fbc58 r11:0x0 r12:0x7ff1b7e87000 r13:0x1a987c0 r14:0x1 r15:0x7ffdde68aa50 rip:0x70000002 eflags:0x6 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7ff1a6490a00 gs_base:0x0
> }
> {
>   global_time:21338, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:17902, ticks:71795858
>  rax:0x0 rbx:0xb rcx:0xffffffffffffffff rdx:0x0 rsi:0x8a38 rdi:0x7ff1b7e87000 rbp:0x7ffdde68aba0 rsp:0x7ffdde68a950 r8:0x17d4ca0 r9:0x0 r10:0x7ff1b06fbc58 r11:0x0 r12:0x7ff1b7e87000 r13:0x1a987c0 r14:0x1 r15:0x7ffdde68aa50 rip:0x70000002 eflags:0x6 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7ff1a6490a00 gs_base:0x0
> }
> {
>   global_time:21339, event:`SYSCALLBUF_FLUSH' tid:17902, ticks:72137042
>   { syscall:'close', ret:0x0, size:0x10 }
>   { syscall:'lstat', ret:0x0, size:0xa0 }
>   { syscall:'lstat', ret:0x0, size:0xa0 }
>   { syscall:'readlink', ret:0x46, size:0x56 }
>   { syscall:'lstat', ret:0x0, size:0xa0 }
>   { syscall:'stat', ret:0x0, size:0xa0 }
>   { syscall:'lstat', ret:0x0, size:0xa0 }
>   { syscall:'lstat', ret:0x0, size:0xa0 }
>   { syscall:'readlink', ret:0x5c, size:0x6c }
>   { syscall:'lstat', ret:0x0, size:0xa0 }
>   { syscall:'stat', ret:0x0, size:0xa0 }
>   { syscall:'time', ret:0x56676032, size:0x10 }
>   { syscall:'open', ret:0x16, size:0x10 }
>   { syscall:'read', ret:0x10, size:0x20 }
>   { syscall:'close', ret:0x0, size:0x10 }
>   { syscall:'gettimeofday', ret:0x0, size:0x20 }
>   { syscall:'stat', ret:0x0, size:0xa0 }
>   { syscall:'open', ret:0x16, size:0x10 }
>   { syscall:'fcntl', ret:0x0, size:0x10 }
> }
> {
>   global_time:21340, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:17902, ticks:72137042
>  rax:0xffffffffffffffda rbx:0x9 rcx:0xffffffffffffffff rdx:0x1 rsi:0x3111 rdi:0x0 rbp:0x7ffdde6895e0 rsp:0x7ffdde689390 r8:0x16 r9:0x0 r10:0x2 r11:0x0 r12:0x7ffdde689c78 r13:0x1b0d080 r14:0x1 r15:0x7ffdde689490 rip:0x70000002 eflags:0x2 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7ff1a6490a00 gs_base:0x0
> }
> {
>   global_time:21341, event:`SYSCALLBUF_RESET' tid:17902, ticks:72137042
> }
> {
>   global_time:21342, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:17902, ticks:72137042
>  rax:0x7ff1b7e8c000 rbx:0x9 rcx:0xffffffffffffffff rdx:0x1 rsi:0x3111 rdi:0x0 rbp:0x7ffdde6895e0 rsp:0x7ffdde689390 r8:0x16 r9:0x0 r10:0x2 r11:0x0 r12:0x7ffdde689c78 r13:0x1b0d080 r14:0x1 r15:0x7ffdde689490 rip:0x70000002 eflags:0x2 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7ff1a6490a00 gs_base:0x0
>   { map_file:"/hdd/builds/build-mozilla-central/mozilla/toolkit/components/promiseworker/PromiseWorker.jsm", addr:0x7ff1b7e8c000, length:0x4000, prot_flags:"r--p", file_offset:0x0 }
>   { addr:0x7ff1b7e8c000, length:0x3111 }
> }
> {
>   global_time:21343, event:`SCHED' tid:17902, ticks:72417207
>  rax:0x0 rbx:0x7ff18eb3fda8 rcx:0x7 rdx:0x10 rsi:0x7ffdde685014 rdi:0x7ff18eb3fda8 rbp:0x7ffdde685000 rsp:0x7ffdde685000 r8:0x0 r9:0x0 r10:0xa r11:0x2 r12:0x7ffdde688a78 r13:0x7ffdde685050 r14:0x10 r15:0x1 rip:0x7ff1b4919d82 eflags:0x10046 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7ff1a6490a00 gs_base:0x0
> }
> {
>   global_time:21344, event:`SYSCALL: futex' (state:EXITING_SYSCALL) tid:17868, ticks:744247
>  rax:0xfffffffffffffff5 rbx:0x7fb9540078e8 rcx:0xffffffffffffffff rdx:0x1 rsi:0x80 rdi:0x7fb9637fdb44 rbp:0x7fb9637fdac0 rsp:0x7fb9637fda60 r8:0x7fb9637fda00 r9:0x0 r10:0x0 r11:0x0 r12:0x7fb9637fdaf0 r13:0x7fb9637fdb40 r14:0x7fb9637fdb18 r15:0xfffffffffff0bdc0 rip:0x7fb9cc2feda0 eflags:0x46 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fb9637fe700 gs_base:0x0
>   { addr:0x7fb9637fdb44, length:0x4 }
> }
>

**Comment by rocallahan** [comment]
OK thanks. I think I need machine access now...

**Comment by rocallahan** [comment]
Actually, I just checked in some debugging improvements so if you pull master and replay, we should get better data.

**Comment by dbaron** [comment]
the output from rr replay -a is now:

> [FATAL /home/dbaron/builds/rr/rr/src/ReplaySession.cc:838:check_ticks_consistency() errno: 0 'Success'] 
>  (task 27149 (rec:27019) at time 71440)
>  ->  Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: rrcall_notify_syscall_hook_exit'; expected 2220680401, got 2257734730
> Launch gdb with
>   gdb /hdd/builds/build-mozilla-central/obj/firefox-debugopt/dist/bin/firefox
> and attach to the rr debug server with:
>   target remote :27149

and then a bit of rr dump -b -m -p is:

> {
>   global_time:71436, event:`SYSCALLBUF_FLUSH' tid:27051, ticks:1517612
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'futex', ret:0x0, size:0x14 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'gettid', ret:0x69ab, size:0x10 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'futex', ret:0x1, size:0x18 }
>   { syscall:'gettid', ret:0x69ab, size:0x10 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'gettimeofday', ret:0x0, size:0x28 }
>   { syscall:'gettid', ret:0x69ab, size:0x10 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'gettid', ret:0x69ab, size:0x10 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'gettimeofday', ret:0x0, size:0x28 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
>   { syscall:'clock_gettime', ret:0x0, size:0x20 }
> }
> {
>   global_time:71437, event:`SYSCALL: futex' (state:ENTERING_SYSCALL) tid:27051, ticks:1517612
>  rax:0xffffffffffffffda rbx:0x7f46628fcb60 rcx:0xffffffffffffffff rdx:0x1 rsi:0x89 rdi:0x7f46628fcb64 rbp:0x7f46628fcae0 rsp:0x7f46628fca30 r8:0x7f46628fcb10 r9:0xffffffff r10:0x7f46628fca98 r11:0x0 r12:0x1 r13:0x7f46628fca98 r14:0xffffffffffffff92 r15:0x4200 rip:0x7f46e77ca149 eflags:0x2 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7f46628fd700 gs_base:0x0
> }
> {
>   global_time:71438, event:`SYSCALLBUF_RESET' tid:27051, ticks:1517612
> }
> {
>   global_time:71439, event:`SYSCALLBUF_FLUSH' tid:27019, ticks:2220680401
>   { syscall:'gettimeofday', ret:0x0, size:0x20 }
>   { syscall:'gettimeofday', ret:0x0, size:0x20 }
>   { syscall:'gettimeofday', ret:0x0, size:0x20 }
>   { syscall:'gettimeofday', ret:0x0, size:0x20 }
> }
> {
>   global_time:71440, event:`SYSCALL: rrcall_notify_syscall_hook_exit' (state:ENTERING_SYSCALL) tid:27019, ticks:2220680401
>  rax:0xffffffffffffffda rbx:0x7f46e7d06078 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x7ffcec80da78 rbp:0x0 rsp:0x7ffcec80d838 r8:0x7ffcec80d970 r9:0x7ffcec80dda0 r10:0x0 r11:0x0 r12:0x0 r13:0x7ffcec80da78 r14:0x7f46e7d06088 r15:0x7ffcec80d928 rip:0x70000012 eflags:0x2 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1bc fs_base:0x7f46e7e07740 gs_base:0x0
> }
> {
>   global_time:71441, event:`SYSCALLBUF_RESET' tid:27019, ticks:2220680401
> }
> {
>   global_time:71442, event:`SYSCALL: rrcall_notify_syscall_hook_exit' (state:EXITING_SYSCALL) tid:27019, ticks:2220680401
>  rax:0x0 rbx:0x7f46e7d06078 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x7ffcec80da78 rbp:0x0 rsp:0x7ffcec80d838 r8:0x7ffcec80d970 r9:0x7ffcec80dda0 r10:0x0 r11:0x0 r12:0x0 r13:0x7ffcec80da78 r14:0x7f46e7d06088 r15:0x7ffcec80d928 rip:0x70000012 eflags:0x2 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x60 fs_base:0x7f46e7e07740 gs_base:0x0
>   { addr:0x7f46e7d06005, length:0x1 }
> }
> {
>   global_time:71443, event:`SYSCALLBUF_FLUSH' tid:27019, ticks:2221483221
>   { syscall:'gettimeofday', ret:0x0, size:0x20 }
>   { syscall:'gettimeofday', ret:0x0, size:0x20 }
> }
>

**Comment by rocallahan** [comment]
Getting the rr test suite to run on your laptop is probably the best bet here...

**Comment by dbaron** [comment]
I upgraded from Ubuntu 15.04 to Ubuntu 15.10, and the bug has now gone away.  (I also updated to rr tip again, but I'm guessing it's more likely to be the Ubuntu update.)

**Comment by rocallahan** [comment]
@theres-waldo --- I think I need your help to work on this now. I'll try next week.

**Comment by rocallahan** [comment]
Hopefully fixed by https://github.com/mozilla/rr/commit/75859fd3c0087731550bdba788880f5a7a393c7d, but who knows...

**Comment by janisozaur** [comment]
On Arch, https://github.com/janisozaur/rr-sdl-test-case still doesn't work, I think it is related, even though is appears to have many faces.

```
$ LIBGL_ALWAYS_SOFTWARE=1 rr ./sdl-test # works just fine…
$ LIBGL_ALWAYS_SOFTWARE=1 rr replay -a /home/janisozaur/.local/share/rr/sdl-test-0
XIO:  fatal IO error 9 (Bad file descriptor) on X server ":0"
      after 203 requests (203 known processed) with 83 events remaining.
[FATAL /tmp/yaourt-tmp-janisozaur/aur-rr-git/src/rr/src/ReplaySession.cc:350:check_pending_sig() errno: 0 'Success'] 
 (task 6295 (rec:6079) at time 3385)
 ->  Assertion `0 < t->pending_sig()' failed to hold. Replaying `SYSCALLBUF_FLUSH': expecting tracee signal or trap, but instead at `exit_group' (ticks: 26977139)
Launch gdb with
  gdb /home/janisozaur/.local/share/rr/sdl-test-0/mmap_1_hardlink_sdl-test
and attach to the rr debug server with:
  target remote :6295
```
Bits from `rr dump -b -m p`:
```
{
  global_time:3378, event:`SYSCALL: brk' (state:EXITING_SYSCALL) tid:6079, ticks:22659925
 eax:0x948b000 ecx:0xf7356000 edx:0x9466000 ebx:0x948b000 esp:0xfff9ac74 ebp:0xf7357df0 esi:0x9466000 edi:0x948b000 eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x2d
  { map_file:"[heap]", addr:0x9466000, length:0x25000, prot_flags:"rw-p", file_offset:0x0 }
}
{
  global_time:3379, event:`SYSCALL: brk' (state:ENTERING_SYSCALL) tid:6079, ticks:23762855
 eax:0xffffffda ecx:0xf7356000 edx:0x948b000 ebx:0x94ad000 esp:0xfff9a334 ebp:0xf7357df0 esi:0x948b000 edi:0x94ad000 eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x2d
}
{
  global_time:3380, event:`SYSCALL: brk' (state:EXITING_SYSCALL) tid:6079, ticks:23762855
 eax:0x94ad000 ecx:0xf7356000 edx:0x948b000 ebx:0x94ad000 esp:0xfff9a334 ebp:0xf7357df0 esi:0x948b000 edi:0x94ad000 eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x2d
  { map_file:"[heap]", addr:0x948b000, length:0x22000, prot_flags:"rw-p", file_offset:0x0 }
}
{
  global_time:3381, event:`SYSCALLBUF_FLUSH' tid:6079, ticks:26028110
  { syscall:'access', ret:0x0, size:0x10 }
  { syscall:'readlink', ret:0x2c, size:0x3c }
  { syscall:'open', ret:0x5, size:0x10 }
  { syscall:'fstat64', ret:0x0, size:0x70 }
}
{
  global_time:3382, event:`SYSCALL: mmap2' (state:ENTERING_SYSCALL) tid:6079, ticks:26028110
 eax:0xffffffda ecx:0x1000 edx:0x3 ebx:0x0 esp:0xfff9af68 ebp:0x0 esi:0x22 edi:0xffffffff eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0xc0
}
{
  global_time:3383, event:`SYSCALLBUF_RESET' tid:6079, ticks:26028110
}
{
  global_time:3384, event:`SYSCALL: mmap2' (state:EXITING_SYSCALL) tid:6079, ticks:26028110
 eax:0xf76cb000 ecx:0x1000 edx:0x3 ebx:0x0 esp:0xfff9af68 ebp:0x0 esi:0x22 edi:0xffffffff eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0xc0
}
{
  global_time:3385, event:`SYSCALLBUF_FLUSH' tid:6079, ticks:26034116
  { syscall:'_llseek', ret:0x0, size:0x18 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'_llseek', ret:0x0, size:0x18 }
  { syscall:'_llseek', ret:0x0, size:0x18 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x1000, size:0x1010 }
  { syscall:'read', ret:0x3ae, size:0x3be }
  { syscall:'close', ret:0x0, size:0x10 }
}
{
  global_time:3386, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:6079, ticks:26034116
 eax:0xffffffda ecx:0x1000 edx:0xf7356000 ebx:0xf76cb000 esp:0xfff9b108 ebp:0xfff9b268 esi:0x9467600 edi:0x0 eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x5b
}
{
  global_time:3387, event:`SYSCALLBUF_RESET' tid:6079, ticks:26034116
}
{
  global_time:3388, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:6079, ticks:26034116
 eax:0x0 ecx:0x1000 edx:0xf7356000 ebx:0xf76cb000 esp:0xfff9b108 ebp:0xfff9b268 esi:0x9467600 edi:0x0 eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x5b
}
{
  global_time:3389, event:`SYSCALL: brk' (state:ENTERING_SYSCALL) tid:6079, ticks:26281694
 eax:0xffffffda ecx:0xf7356000 edx:0x94ad000 ebx:0x94d5000 esp:0xfff9a3e4 ebp:0xf7357df0 esi:0x94ad000 edi:0x94d5000 eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x2d
}
{
  global_time:3390, event:`SYSCALL: brk' (state:EXITING_SYSCALL) tid:6079, ticks:26281694
 eax:0x94d5000 ecx:0xf7356000 edx:0x94ad000 ebx:0x94d5000 esp:0xfff9a3e4 ebp:0xf7357df0 esi:0x94ad000 edi:0x94d5000 eip:0x70000012 eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x2d
  { map_file:"[heap]", addr:0x94ad000, length:0x28000, prot_flags:"rw-p", file_offset:0x0 }
}
```

**Comment by rocallahan** [comment]
@janisozaur, I fixed your bug in commit 987526eb6eea48ac7fe480795516729768ee978d. That's 32-bit only so probably not the same as this bug. Thanks for reporting it though, it's a regression that's good to have fixed.

**Comment by rocallahan** [comment]
I'll mark this fixed. New divergence bugs can go into new issues.
