### ISSUE TITLE
Unknown ioctl(0x8004551a): type:0x55 nr:0x1a dir:0x2 size:4 addr:0x1147910

### ISSUE THREAD

**Issue by montanier** [mozilla/rr#1693]
Hello,

I tried to run a code linking to Openni2 with rr and got the following error

```
rr: Saving the execution of `trackVideo' to trace directory `/home/jmmontanier/.local/share/rr/trackVideo-2'.
After initialization:

 [FATAL /home/jmmontanier/rr/rr/src/record_syscall.cc:3678:rec_process_syscall_arch() errno: SUCCESS] 
 (task 15553 (rec:15553) at time 2514)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result 0 (errno SUCCESS); Unknown ioctl(0x8004551a): type:0x55 nr:0x1a dir:0x2 size:4 addr:0x1147910
Launch gdb with
  gdb /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/trackVideo
and attach to the rr debug server with:
  target remote :15553
```

Here is the corresponding backtrace from gdb:
```
#0  0x0000000070000002 in ?? ()
#1  0x00007f5803092198 in _raw_syscall () at /home/jmmontanier/rr/rr/src/preload/raw_syscall.S:120
#2  0x00007f580308f235 in traced_raw_syscall (call=call@entry=0x7fffc8809760)
    at /home/jmmontanier/rr/rr/src/preload/preload.c:293
#3  0x00007f5803090478 in syscall_hook_internal (call=0x7fffc8809760)
    at /home/jmmontanier/rr/rr/src/preload/preload.c:2397
#4  syscall_hook (call=0x7fffc8809760) at /home/jmmontanier/rr/rr/src/preload/preload.c:2405
#5  0x00007f58030921ca in _syscall_hook_trampoline () at /home/jmmontanier/rr/rr/src/preload/syscall_hook.S:213
#6  0x00007f58030921db in _syscall_hook_trampoline_48_3d_01_f0_ff_ff ()
    at /home/jmmontanier/rr/rr/src/preload/syscall_hook.S:255
#7  0x00007f58030929a8 in _stub_buffer () at /home/jmmontanier/rr/rr/src/preload/syscall_hook.S:382
#8  0x00007f5801cef33a in ioctl () at ../sysdeps/unix/syscall-template.S:81
#9  0x00007f57fd046ebd in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#10 0x00007f57fd03db03 in libusb_open () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#11 0x00007f57fd2d16d8 in xnUSBOpenDeviceImpl.part.0 ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#12 0x00007f57fd2d1ca4 in xnUSBOpenDeviceByPath ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#13 0x00007f57fd284d5f in XnSensorIO::OpenDevice(char const*) ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#14 0x00007f57fd2947ef in XnSensor::InitSensor(XnDeviceConfig const*) ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#15 0x00007f57fd297901 in XnSensor::InitImpl(XnDeviceConfig const*) ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#16 0x00007f57fd26d8c8 in XnDeviceBase::Init(XnDeviceConfig const*) ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#17 0x00007f57fd27b077 in XnOniDevice::Init(char const*) ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#18 0x00007f57fd27bed7 in XnOniDriver::deviceOpen(char const*, char const*) ()
   from /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/DepthPicture/OpenNI2/Drivers/libPS1080.so
#19 0x00007f5802e1f6f2 in oni::implementation::Device::open(char const*) () from ./libOpenNI2.so
#20 0x0000000000402fd9 in openni::Device::open (this=0x7fffc880a400, uri=0x0)
    at /home/jmmontanier/proto_team/appu_applications/Skeleton_tracker/OpenNI2/Packaging/Final/OpenNI-Linux-x64-2.2/Include/OpenNI.h:2671
#21 0x0000000000402540 in main (argc=1, argv=0x7fffc88146b8) at trackVideo.cpp:28

```

**Comment by rocallahan** [comment]
It probably isn't too hard to add support for the USB ioctls, but I don't know how to write automated tests since it doesn't seem safe to just open whatever we can find in `/dev/usb` and start doing ioctls on it.

**Comment by rocallahan** [comment]
I pushed some USB support to master. Try it! I got it working on a simple libuvc example but I didn't find an easy way to test the libusb functionality Openni2 seems to use, so I'm not 100% confident...

**Comment by montanier** [comment]
Thanks for taking into account the problem. However with the latest version of master, I have the following compile error
```
[ 97%] Building CXX object CMakeFiles/rr.dir/src/RecordTask.cc.o
/home/jmmontanier/rr/rr/src/record_syscall.cc: In function ‘rr::Switchable rr::prepare_ioctl(rr::RecordTask*, rr::TaskSyscallState&)’:
/home/jmmontanier/rr/rr/src/record_syscall.cc:1296:26: error: ‘USBDEVFS_ALLOC_STREAMS’ was not declared in this scope
     case IOCTL_MASK_SIZE(USBDEVFS_ALLOC_STREAMS):
                          ^
/home/jmmontanier/rr/rr/src/record_syscall.cc:1140:30: note: in definition of macro ‘IOCTL_MASK_SIZE’
 #define IOCTL_MASK_SIZE(v) ((v) & ~(_IOC_SIZEMASK << _IOC_SIZESHIFT))
                              ^
/home/jmmontanier/rr/rr/src/record_syscall.cc:1300:26: error: ‘USBDEVFS_FREE_STREAMS’ was not declared in this scope
     case IOCTL_MASK_SIZE(USBDEVFS_FREE_STREAMS):
                          ^
/home/jmmontanier/rr/rr/src/record_syscall.cc:1140:30: note: in definition of macro ‘IOCTL_MASK_SIZE’
 #define IOCTL_MASK_SIZE(v) ((v) & ~(_IOC_SIZEMASK << _IOC_SIZESHIFT))
```

This error persist even after re-creating the build folder (I am using the cmake method).

**Comment by rocallahan** [comment]
Should be fixed by https://github.com/mozilla/rr/commit/cdcde88bd634797d467f2da67f1d5402e0b5c9a3

**Comment by montanier** [comment]
Yes perfect, and now I can record and replay my program. Thanks :)
