### ISSUE TITLE
Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: mmap'

### ISSUE THREAD

**Issue by sitaowang1998** [mozilla/rr#2519]
When I run `rr replay`, I get the following error.

```
[FATAL /home/anygroup/rr/rr/src/ReplaySession.cc:1038:check_ticks_consistency()] 
 (task 31368 (rec:30918) at time 49)
 -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: mmap'; expected 110480, got 114246
```

<details>
  <summary>Full output</summary>

```
 [FATAL /home/anygroup/rr/rr/src/ReplaySession.cc:1038:check_ticks_consistency()] 
 (task 31368 (rec:30918) at time 49)
 -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: mmap'; expected 110480, got 114246
Tail of trace dump:
{
  real_time:6885469.152992 global_time:29, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:30918, ticks:86
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0xb rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.153045 global_time:30, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:30918, ticks:86
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0xb rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:30918, addr:0x7ffccc29ee20, length:0x20 }
}
{
  real_time:6885469.153270 global_time:31, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:30918, ticks:97
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0xd rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.153326 global_time:32, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:30918, ticks:97
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0xd rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:30918, addr:0x7ffccc29ee20, length:0x20 }
}
{
  real_time:6885469.153552 global_time:33, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:30918, ticks:111
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0x10 rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.153605 global_time:34, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:30918, ticks:111
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0x10 rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:30918, addr:0x7ffccc29ee20, length:0x20 }
}
{
  real_time:6885469.153831 global_time:35, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:30918, ticks:159
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0x1f rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.153884 global_time:36, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:30918, ticks:159
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffccc29ee20 rdi:0x1f rbp:0x0 rsp:0x7ffccc29ede8 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:30918, addr:0x7ffccc29ee20, length:0x20 }
}
{
  real_time:6885469.154142 global_time:37, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:30918, ticks:3627
rax:0xffffffffffffffda rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x3d rsp:0x7ffccc29ede0 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.154202 global_time:38, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:30918, ticks:3627
rax:0x7fdb01053000 rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x3d rsp:0x7ffccc29ede0 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7fdb01053000, length:0x20000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x20000 }
}
{
  real_time:6885469.154432 global_time:39, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:30918, ticks:4707
rax:0xffffffffffffffda rbx:0x100000 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0xf840000000 rbp:0x516030 rsp:0x7ffccc29eba8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.154491 global_time:40, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:30918, ticks:4707
rax:0xf840000000 rbx:0x100000 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0xf840000000 rbp:0x516030 rsp:0x7ffccc29eba8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0xf840000000, length:0x100000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x100000 }
}
{
  real_time:6885469.154709 global_time:41, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:30918, ticks:4714
rax:0xffffffffffffffda rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x10000 rdi:0xf83fff0000 rbp:0x516030 rsp:0x7ffccc29eb78 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.154774 global_time:42, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:30918, ticks:4714
rax:0xf83fff0000 rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x10000 rdi:0xf83fff0000 rbp:0x516030 rsp:0x7ffccc29eb78 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0xf83fff0000, length:0x10000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x10000 }
}
{
  real_time:6885469.154994 global_time:43, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:30918, ticks:4723
rax:0xffffffffffffffda rbx:0x10 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x516030 rsp:0x7ffccc29eba8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.155057 global_time:44, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:30918, ticks:4723
rax:0x7fdb01033000 rbx:0x10 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x516030 rsp:0x7ffccc29eba8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7fdb01033000, length:0x20000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x20000 }
}
{
  real_time:6885469.155320 global_time:45, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:30918, ticks:18585
rax:0xffffffffffffffda rbx:0xd0 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x0 rsp:0x7ffccc29ed78 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.155383 global_time:46, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:30918, ticks:18585
rax:0x7fdb01013000 rbx:0xd0 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x0 rsp:0x7ffccc29ed78 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7fdb01013000, length:0x20000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x20000 }
}
{
  real_time:6885469.155616 global_time:47, event:`SYSCALL: sigaltstack' (state:ENTERING_SYSCALL) tid:30918, ticks:19762
rax:0xffffffffffffffda rbx:0xf840005000 rcx:0xffffffffffffffff rdx:0x8000 rsi:0x0 rdi:0x7ffccc29ee98 rbp:0xf840005000 rsp:0x7ffccc29ee70 r8:0x8 r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x4129e4 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x83 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.155654 global_time:48, event:`SYSCALL: sigaltstack' (state:EXITING_SYSCALL) tid:30918, ticks:19762
rax:0x0 rbx:0xf840005000 rcx:0xffffffffffffffff rdx:0x8000 rsi:0x0 rdi:0x7ffccc29ee98 rbp:0xf840005000 rsp:0x7ffccc29ee70 r8:0x8 r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x4129e4 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x83 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.156572 global_time:49, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:30918, ticks:110480
rax:0xffffffffffffffda rbx:0x1000111 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0x0 rbp:0xf840030ba0 rsp:0x7fdb01015ac8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x519 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:6885469.156639 global_time:50, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:30918, ticks:110480
rax:0x7fdb00f13000 rbx:0x1000111 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0x0 rbp:0xf840030ba0 rsp:0x7fdb01015ac8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x519 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7fdb00f13000, length:0x100000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x100000 }
}
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x45)[0x8b0099]
rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0x196)[0x738600]
rr[0x75f006]
rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x5a)[0x75f244]
rr(_ZN2rr13ReplaySession23check_ticks_consistencyEPNS_10ReplayTaskERKNS_5EventE+0x11a)[0x81857e]
rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x782)[0x81bbd6]
rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandEl+0x100)[0x834b50]
rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0x5a2)[0x7359c2]
rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x4c9)[0x737771]
rr[0x811a8f]
rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x3f0)[0x812492]
rr(main+0x21b)[0x8ca3cc]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fa2e983c830]
rr(_start+0x29)[0x6a7b79]
=== End rr backtrace
```
</details>

I am using the master branch with latest commit 9cc1b4a231163daea57416295f418e7997cbfd26. The linux version is as bellow.

```
~$ uname -a
Linux anygroup-PowerEdge-R420 4.0.1-040001-generic #201505081133 SMP Fri May 8 15:34:52 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Keno** [comment]
You'll need to be more specific as to what you were trying to record. This kind of error is a general replay divergence, which can be caused by anything from hardware bugs to kernel problems to issues in rr itself.

**Comment by sitaowang1998** [comment]
I am trying to run a compiled go program that unzip a zip file for 1000 times for testing. I have attached the compiled binary. The zip file I am testing with is too large to be included.
[909_ziptest_exe.zip](https://github.com/mozilla/rr/files/4500413/909_ziptest_exe.zip)

**Comment by Keno** [comment]
Can you try running the rr tests to see if everything is otherwise ok?

**Comment by sitaowang1998** [comment]
No. A lot of tests failed. I attach part of the test results.
[test.log](https://github.com/mozilla/rr/files/4500443/test.log)

**Comment by Keno** [comment]
Looks like a lot of tasks are being killed unexpectedly. Do you have some sort of security module running? Also check dmesg for any messages.

**Comment by sitaowang1998** [comment]
From dimes I can see some segfault.
<details>
  <summary>dmesg error log</summary>
```
[6890665.674329] rr[337]: segfault at 30 ip 0000000000878fc4 sp 00007ffeef323650 error 4 in rr[400000+689000]
[6890691.575013] rr[571]: segfault at 30 ip 0000000000878fc4 sp 00007ffdf0fd44e0 error 4 in rr[400000+689000]
[6890717.305586] rr[732]: segfault at 30 ip 0000000000878fc4 sp 00007ffcba0b0ae0 error 4 in rr[400000+689000]
[6890746.489277] rr[1192]: segfault at 30 ip 0000000000878fc4 sp 00007ffe24c65b30 error 4 in rr[400000+689000]
[6890759.237801] rr[1243]: segfault at 30 ip 0000000000878fc4 sp 00007ffdf412f880 error 4 in rr[400000+689000]
[6890811.737045] rr[2086]: segfault at 30 ip 0000000000878fc4 sp 00007ffe67a28cf0 error 4 in rr[400000+689000]
[6890837.854372] rr[2332]: segfault at 30 ip 0000000000878fc4 sp 00007fff0aba41f0 error 4 in rr[400000+689000]
[6890864.072878] rr[2576]: segfault at 30 ip 0000000000878fc4 sp 00007ffd2ff66380 error 4 in rr[400000+689000]
[6890891.683850] rr[2831]: segfault at 30 ip 0000000000878fc4 sp 00007ffe1c5f3d90 error 4 in rr[400000+689000]
[6890942.548504] rr[3944]: segfault at 30 ip 0000000000878fc4 sp 00007ffcba6c68f0 error 4 in rr[400000+689000]
[6890968.443446] rr[4174]: segfault at 30 ip 0000000000878fc4 sp 00007ffe371f04e0 error 4 in rr[400000+689000]
[6890994.179373] rr[4334]: segfault at 30 ip 0000000000878fc4 sp 00007ffd19941060 error 4 in rr[400000+689000]
[6891023.359890] rr[4746]: segfault at 30 ip 0000000000878fc4 sp 00007ffd5b412820 error 4 in rr[400000+689000]
[6891036.109997] rr[4789]: segfault at 30 ip 0000000000878fc4 sp 00007ffd31f9fa60 error 4 in rr[400000+689000]
[6891088.607951] rr[5324]: segfault at 30 ip 0000000000878fc4 sp 00007ffebd348850 error 4 in rr[400000+689000]
[6891114.721970] rr[5568]: segfault at 30 ip 0000000000878fc4 sp 00007fff26a31be0 error 4 in rr[400000+689000]
[6891140.943440] rr[5812]: segfault at 30 ip 0000000000878fc4 sp 00007fff4ea32da0 error 4 in rr[400000+689000]
[6891168.573811] rr[6069]: segfault at 30 ip 0000000000878fc4 sp 00007fffa5eab9e0 error 4 in rr[400000+689000]
[6891290.850840] rr[14590]: segfault at 30 ip 0000000000878fc4 sp 00007ffcb1409640 error 4 in rr[400000+689000]
[6891440.047411] rr[3774]: segfault at 30 ip 0000000000878fc4 sp 00007ffce8151f10 error 4 in rr[400000+689000]
[6891451.231596] rr[4442]: segfault at 30 ip 0000000000878fc4 sp 00007fff20a11bc0 error 4 in rr[400000+689000]
[6891544.663239] rr[9373]: segfault at 258 ip 00000000006ba558 sp 00007ffc0d770240 error 4 in rr[400000+689000]
[6891568.382669] rr[9415]: segfault at 30 ip 0000000000878fc4 sp 00007ffc620ec6c0 error 4 in rr[400000+689000]
[6891581.399206] rr[9497]: segfault at 258 ip 00000000006ba558 sp 00007ffdf5fce490 error 4 in rr[400000+689000
```
</details>

I tried to use the 5.3.0 release version. It has passed all the tests, but still fails on replaying for a similar error.

<details>
  <summary>rr error log</summary>
```
[FATAL /home/anygroup/rr/rr/src/ReplaySession.cc:1032:check_ticks_consistency()] 
 (task 7596 (rec:32704) at time 49)
 -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: mmap'; expected 107952, got 111718
Tail of trace dump:
{
  real_time:78303.807183 global_time:29, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:32704, ticks:86
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0xb rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.807234 global_time:30, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:32704, ticks:86
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0xb rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:32704, addr:0x7ffd69c592b0, length:0x20 }
}
{
  real_time:78303.807451 global_time:31, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:32704, ticks:97
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0xd rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.807504 global_time:32, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:32704, ticks:97
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0xd rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:32704, addr:0x7ffd69c592b0, length:0x20 }
}
{
  real_time:78303.807721 global_time:33, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:32704, ticks:111
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0x10 rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.807771 global_time:34, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:32704, ticks:111
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0x10 rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:32704, addr:0x7ffd69c592b0, length:0x20 }
}
{
  real_time:78303.807988 global_time:35, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:32704, ticks:159
rax:0xffffffffffffffda rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0x1f rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.808055 global_time:36, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:32704, ticks:159
rax:0x0 rbx:0x4fab80 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd69c592b0 rdi:0x1f rbp:0x0 rsp:0x7ffd69c59278 r8:0x0 r9:0x0 r10:0x8 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x412887 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0xd fs_base:0x4fb1c8 gs_base:0x0
  { tid:32704, addr:0x7ffd69c592b0, length:0x20 }
}
{
  real_time:78303.808317 global_time:37, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:32704, ticks:3627
rax:0xffffffffffffffda rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x3d rsp:0x7ffd69c59270 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.808374 global_time:38, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:32704, ticks:3627
rax:0x7f6f1c37a000 rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x3d rsp:0x7ffd69c59270 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7f6f1c37a000, length:0x20000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x20000 }
}
{
  real_time:78303.808596 global_time:39, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:32704, ticks:4707
rax:0xffffffffffffffda rbx:0x100000 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0xf840000000 rbp:0x516030 rsp:0x7ffd69c59038 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.808652 global_time:40, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:32704, ticks:4707
rax:0xf840000000 rbx:0x100000 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0xf840000000 rbp:0x516030 rsp:0x7ffd69c59038 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0xf840000000, length:0x100000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x100000 }
}
{
  real_time:78303.808860 global_time:41, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:32704, ticks:4714
rax:0xffffffffffffffda rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x10000 rdi:0xf83fff0000 rbp:0x516030 rsp:0x7ffd69c59008 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.808921 global_time:42, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:32704, ticks:4714
rax:0xf83fff0000 rbx:0x511828 rcx:0xffffffffffffffff rdx:0x7 rsi:0x10000 rdi:0xf83fff0000 rbp:0x516030 rsp:0x7ffd69c59008 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0xf83fff0000, length:0x10000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x10000 }
}
{
  real_time:78303.809127 global_time:43, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:32704, ticks:4723
rax:0xffffffffffffffda rbx:0x10 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x516030 rsp:0x7ffd69c59038 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.809186 global_time:44, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:32704, ticks:4723
rax:0x7f6f1c35a000 rbx:0x10 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x516030 rsp:0x7ffd69c59038 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7f6f1c35a000, length:0x20000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x20000 }
}
{
  real_time:78303.809598 global_time:45, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:32704, ticks:17134
rax:0xffffffffffffffda rbx:0xd0 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x0 rsp:0x7ffd69c59208 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.809659 global_time:46, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:32704, ticks:17134
rax:0x7f6f1c33a000 rbx:0xd0 rcx:0xffffffffffffffff rdx:0x7 rsi:0x20000 rdi:0x0 rbp:0x0 rsp:0x7ffd69c59208 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7f6f1c33a000, length:0x20000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x20000 }
}
{
  real_time:78303.809881 global_time:47, event:`SYSCALL: sigaltstack' (state:ENTERING_SYSCALL) tid:32704, ticks:18307
rax:0xffffffffffffffda rbx:0xf840006000 rcx:0xffffffffffffffff rdx:0x8000 rsi:0x0 rdi:0x7ffd69c59328 rbp:0xf840006000 rsp:0x7ffd69c59300 r8:0x8 r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x4129e4 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x83 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.809918 global_time:48, event:`SYSCALL: sigaltstack' (state:EXITING_SYSCALL) tid:32704, ticks:18307
rax:0x0 rbx:0xf840006000 rcx:0xffffffffffffffff rdx:0x8000 rsi:0x0 rdi:0x7ffd69c59328 rbp:0xf840006000 rsp:0x7ffd69c59300 r8:0x8 r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x0 r14:0x0 r15:0x0 rip:0x4129e4 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x83 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.810483 global_time:49, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:32704, ticks:107952
rax:0xffffffffffffffda rbx:0x1000111 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0x0 rbp:0xf840031ba0 rsp:0x7f6f1c33cac8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x519 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:78303.810545 global_time:50, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:32704, ticks:107952
rax:0x7f6f1c23a000 rbx:0x1000111 rcx:0xffffffffffffffff rdx:0x7 rsi:0x100000 rdi:0x0 rbp:0xf840031ba0 rsp:0x7f6f1c33cac8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x0 r13:0x519 r14:0x0 r15:0x0 rip:0x41290c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x63 gs:0x0 orig_rax:0x9 fs_base:0x4fb1c8 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7f6f1c23a000, length:0x100000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x100000 }
}
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x45)[0x899f95]
rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0x196)[0x72c20c]
rr[0x7510d8]
rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x5a)[0x751316]
rr(_ZN2rr13ReplaySession23check_ticks_consistencyEPNS_10ReplayTaskERKNS_5EventE+0x11a)[0x805802]
rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x742)[0x808920]
rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandEl+0x100)[0x822b6a]
rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0x5a2)[0x7295f6]
rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x4c9)[0x72b38f]
rr[0x7fee1c]
rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x3eb)[0x7ff807]
rr(main+0x21b)[0x8b250a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fc577a26830]
rr(_start+0x29)[0x69da59]
=== End rr backtrace
```
</details>

**Comment by jrenx** [comment]
We have changed the kernel version and the tests are all passing. 
However, we are still seeing the same error. 
We also tried different kernel versions on Ubuntu 16 and one 2 different types of CPUs, the error is consistently reproducible. 
Please let us know what additional information you need to reproduce this error.

**Comment by jrenx** [comment]
`#include <signal.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/signal.h>
#include <sys/mman.h>
int main(int argc, char *argv[])
{

        void *addr = (void *)syscall(SYS_mmap, NULL, 131072, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);

        addr = (void *)syscall(SYS_mmap, 0xf840000000, 1048576, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);


        addr = (void *)syscall(SYS_mmap, 0xf83fff0000, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);

        addr = (void *)syscall(SYS_mmap, NULL, 131072, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);

        addr = (void *)syscall(SYS_mmap, NULL, 131072, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);

        stack_t ss;
        ss.ss_sp=(void*)0xf840006000;
        ss.ss_flags=0;
        ss.ss_size=32768;
        int ret = sigaltstack(&ss, NULL);

        addr = (void *)syscall(SYS_mmap, NULL, 1048576, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
}`

**Comment by jrenx** [comment]
Wrote a simple test program (in the attachment) which does the system calls done by the program till the error occurred, but excludes the rt_sigaction calls (haven't figured out how to do them), and RR does work for this program. Is it possible that the error is related to the rt_sigaction calls? Another interesting thing we noticed is that RR works for the same program in 32bit and not in 64bit...
[test.txt](https://github.com/mozilla/rr/files/4514312/test.txt)

**Comment by jrenx** [comment]
[syscalls.txt](https://github.com/mozilla/rr/files/4514329/syscalls.txt)

attaching the list of system calls till the error occurred (the error occurred at the last system call). (This is kind of redundant as the RR output file already lists the list of system calls ...)

**Comment by jrenx** [comment]
Also, the error was reproducible on systems older than Linux 4.5
on newer systems (4.20 in this case), RR fails during recording instead of replaying, and it also fails where the problematic mmap occurred ... attaching the error file
[out.txt](https://github.com/mozilla/rr/files/4514450/out.txt)

**Comment by Keno** [comment]
I can reproduce the error during record. Looks like it's in the vsyscall page and having trouble reading that memory. I'm not too familiar with that code. @rocallahan what's supposed to happen with vsyscall?

**Comment by rocallahan** [comment]
The vsyscall page is weird. At least in the past, we couldn't read it via /proc/.../mem. We can't munmap it, and we can't mmap it, because it lives above the user-kernel boundary at least on x86-64. My understanding is that it's always at 0xffffffffff600000. Maybe it moves around sometimes between kernel versions, but if it does, we can't fix its address.

**Comment by Keno** [comment]
Yes, it's at `0xffffffffff600000`, which isn't mapped, so you can't map it, but the kernel will emulate a syscall (including seccomp trap) if you jump to that address.

**Comment by Keno** [comment]
(Or rather it'll emulate `syscall; retq`)

**Comment by Keno** [comment]
However, looks like it may not be emulating a ptrace syscall enter trap, so we don't see it during replay? Could that be?

**Comment by rocallahan** [comment]
On my system we die during recording because get_syscall_instruction_arch is failing, because we can't read the instruction via /proc/.../maps.

**Comment by Keno** [comment]
Yes, I see the same, so I tried to patch that with:
```
diff --git a/src/Task.cc b/src/Task.cc
index 91d882eb..3f481706 100644
--- a/src/Task.cc
+++ b/src/Task.cc
@@ -2561,8 +2561,19 @@ bool Task::ptrace_if_alive(int request, remote_ptr<void> addr, void* data) {
   return true;
 }
 
+static bool is_in_vsyscall(remote_code_ptr ip)
+{
+  // This is hardcoded by the Linux ABI
+  remote_code_ptr vsyscall_start = 0xffffffffff600000;
+  remote_code_ptr vsyscall_end = 0xffffffffff601000;
+  return vsyscall_start <= ip && ip < vsyscall_end;
+}
+
 SupportedArch Task::detect_syscall_arch() {
   SupportedArch syscall_arch;
+  if (is_in_vsyscall(regs().ip())) {
+    return arch();
+  }
   bool ok = get_syscall_instruction_arch(
       this, regs().ip().decrement_by_syscall_insn_length(arch()),
       &syscall_arch);
```
but it ends up diverging during replay at the next syscall. Which I think is because PTRACE_SYSEMU, doesn't stop at the vsyscall.

**Comment by rocallahan** [comment]
Looks like `emulate_vsyscall` bypasses the regular syscall handling path so no surprise it doesn't handle PTRACE_SYSEMU.

**Comment by rocallahan** [comment]
Are we actually recording the vsyscall properly? I would have thought not

**Comment by rocallahan** [comment]
Ah we are because of the seccomp ptrace trap.

**Comment by Keno** [comment]
Ah, I don't think so. I think it's taking the next syscall entry trap and thinks it belongs to get vsyscall, but it doesn't:
```
{
  real_time:2004297.043673 global_time:54, event:`SYSCALL: gettimeofday' (state:ENTERING_SYSCALL) tid:3429380, ticks:169764
rax:0xffffffffffffffda rbx:0x4f98e8 rcx:0xffffffffffffffff rdx:0x1 rsi:0x0 rdi:0x7efeadf57ce0 rbp:0xf84000f060 rsp:0x7efeadf57cd0 r8:0xf840000000 r9:0xf83ffffdf8 r10:0x0 r11:0x246 r12:0x0 r13:0x6 r14:0x0 r15:0x0 rip:0xffffffffff600000 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x60 fs_base:0x4fb1c8 gs_base:0x0
}
{
  real_time:2004297.043881 global_time:55, event:`SYSCALL: gettimeofday' (state:EXITING_SYSCALL) tid:3429380, ticks:169764
rax:0xffffffffffffffda rbx:0x0 rcx:0x4127ef rdx:0x7 rsi:0x4f8e91 rdi:0x2 rbp:0xa rsp:0x7efeadf57e60 r8:0xf840011000 r9:0xf83ffffdf8 r10:0x0 r11:0x202 r12:0x0 r13:0x6 r14:0x0 r15:0x0 rip:0x4127ef eflags:0x202 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x4fb1c8 gs_base:0x0
}
```

**Comment by rocallahan** [comment]
We're recording the entry correctly but the exit is wrong.

**Comment by Keno** [comment]
Yes

**Comment by rocallahan** [comment]
This was fixed in Go in 2012. https://github.com/golang/go/issues/1933
I'm not really enthusiastic about fixing bugs that only affect binaries > 7 years old...

**Comment by rocallahan** [comment]
Er, binaries built using > 7 year old toolchains I suppose.

**Comment by rocallahan** [comment]
I guess we would need to special-case record and replay of syscalls in the vsyscall page. We can't set a breakpoint in the vsyscall page. Maybe we can singlestep through the syscall.

**Comment by Keno** [comment]
Also an issue on systems with very old libcs apparently. I just got a report today (quite coincidentally) that had the same symptoms (though I've yet hear back whether it's actually the same issue) on a system on which we run old OSes (since some of our users still have those *cough* RHEL *cough*).

**Comment by rocallahan** [comment]
I tried with gdb. We can't set a hardware breakpoint on 0xffffffffff600000. Singlestepping with RIP=0xffffffffff600000 stops after executing one instruction after the `ret`.

**Comment by Keno** [comment]
I think the only reasonable options are to either set a seccomp filter during replay, so we get a trap, or to force this case to be monkeypatchable and then emulating it ourselves.

**Comment by rocallahan** [comment]
I guess that makes some kind of sense: the kernel traps, emulates the syscall and ret, and then returns to userspace with TF set.

**Comment by rocallahan** [comment]
Monkeypatch how?

**Comment by rocallahan** [comment]
You mean monkeypatch the caller?

**Comment by rocallahan** [comment]
This is the Go caller:
```
   0x000000000041283b <+0>:	sub    $0x20,%rsp
   0x000000000041283f <+4>:	lea    0x8(%rsp),%rdi
   0x0000000000412844 <+9>:	xor    %rsi,%rsi
   0x0000000000412847 <+12>:	mov    $0xffffffffff600000,%rax
   0x000000000041284e <+19>:	callq  *%rax
   0x0000000000412850 <+21>:	mov    0x8(%rsp),%rbx
=> 0x0000000000412855 <+26>:	mov    0x28(%rsp),%rdi
   0x000000000041285a <+31>:	mov    %rbx,(%rdi)
   0x000000000041285d <+34>:	mov    0x10(%rsp),%ebx
   0x0000000000412861 <+38>:	mov    0x30(%rsp),%rdi
   0x0000000000412866 <+43>:	mov    %ebx,(%rdi)
   0x0000000000412868 <+45>:	add    $0x20,%rsp
   0x000000000041286c <+49>:	retq   
```

**Comment by Keno** [comment]
Yes, monkeypatch the
```
   0x0000000000412847 <+12>:	mov    $0xffffffffff600000,%rax
   0x000000000041284e <+19>:	callq  *%rax
```
into a jump to somewhere we control to emulate the vsyscall. And then just assert that everything has exactly that pattern. That seems to be the case for the uses in go. I'll need to check about old libc.

**Comment by rocallahan** [comment]
Patching it into a jump to the VSDO would be good. We can probably record it as a PATCH_SYSCALL and have it special-case that.

**Comment by Keno** [comment]
Here's the disassembly from the old libc (2.12 from 2010) for the issue that got reported to me:
```
(gdb) f 1
#1  0x00007f3aeceb082d in time () from /lib64/libc.so.6
(gdb) disass
Dump of assembler code for function time:
   0x00007f3aeceb0820 <+0>:     sub    $0x8,%rsp
   0x00007f3aeceb0824 <+4>:     mov    $0xffffffffff600400,%rax
   0x00007f3aeceb082b <+11>:    callq  *%rax
=> 0x00007f3aeceb082d <+13>:    add    $0x8,%rsp
   0x00007f3aeceb0831 <+17>:    retq   
```

**Comment by staticfloat** [comment]
Indeed; this is libc from CentOS 6.9.

**Comment by jrenx** [comment]
Thanks so much!
I can confirm the root cause can be tracked down to a vsyscall.

**Comment by Keno** [comment]
> CentOS 6.9.

That's not as old as I thought (2017)

**Comment by Keno** [comment]
Alright, I'm gonna have a go at doing the proper fix here. I imagine there's probably gonna be additional subtleties related to the strange seccomp stop. Looks like if we try to change the registers during this seccomp stop (to anything other than a skip), the kernel will get mad at us and kill us with SIGSYS, so we'll probably want to set a breakpoint at the return address to get us out of there.

**Comment by Keno** [comment]
Should be fixed on master

**Comment by ntrrgc** [comment]
I can still reproduce it on master as of 64ba09af76528e549dc479f7d6ade1a16903e31f, while running WebKitGTK WebProcess. I can provide a `rr pack` file if someone requests it, but it's a bit unwieldly at 5 GB in size.

**Comment by Keno** [comment]
Reproduce as in you're getting a similar error message or as in you're seeing vsyscall related issues? That error message is quite generic as it is one of the many ways a replay divergence manifests.

**Comment by ntrrgc** [comment]
Okay, you're right, there is no vsyscall mention, it just fails with the same assertion.

**Comment by Keno** [comment]
Probably file a new issue then. We'll need the same information. The rr pack file will be useful also

**Comment by khuey** [comment]
Sounds like as filed this is fixed, please reopen if I'm wrong.
